name    'davidb-dhcpd'
version '0.1.0'
source 'https://bitbucket.org/archidevlm/frlm-tech-puppet'
author 'davidb'
license 'Apache License, Version 2.0'
summary 'dhcpd module'
description 'configure isc-dhcpd service'
project_page 'https://bitbucket.org/archidevlm/frlm-tech-puppet'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
